name: "Detekt result comment"
description: "Leave a detekt result comment on pull request."
author: "pooi (Taewoo You)"

inputs:
  github-token:
    description: "secrets.GITHUB_TOKEN value"
    required: true
  xml-detekt-report-path:
    description: 'The detekt report path (xml)'
    required: true
  html-detekt-report-path:
    description: 'The detekt report path (html)'
    required: true

runs:
  using: composite
  steps:
    - run: pip3 install -r $GITHUB_ACTION_PATH/requirements.txt
      shell: bash
    - name: Parsing detekt result
      shell: bash
      run: |
        $GITHUB_ACTION_PATH/main.py ${{ inputs.xml-detekt-report-path }} ${{ inputs.html-detekt-report-path }} ${{ inputs.github-token }} ${{ github.api_url }} ${{ github.repository }} ${{ github.ref }} ${{ github.event.pull_request.url }}
